sprints5/sprint5_zad8/urban_project/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.advertisement_list, name='advertisement_list'),
    path('advertisement/<int:pk>/', views.advertisement_detail, name='advertisement_detail'),
    path('add/', views.add_advertisement, name='add_advertisement'),
    path('advertisement/<int:pk>/edit/', views.edit_advertisement, name='edit_advertisement'),  # Новый URL для редактирования
    path('advertisement/<int:pk>/delete/', views.delete_advertisement, name='delete_advertisement'),  # Новый URL для удаления объявления
    path('advertisement/<int:pk>/like/', views.like_advertisement, name='like_advertisement'),   # Новый URL для лайка
    path('advertisement/<int:pk>/dislike/', views.dislike_advertisement, name='dislike_advertisement'),  # Новый URL для дизлайка
]

"""
URL-шаблоны для приложения 'board'.

Доступные маршруты:
- '' (Путь к списку объявлений)
- 'advertisement/<int:pk>/' (Путь к деталям объявления по его первичному ключу)
- 'add/' (Путь к форме добавления нового объявления)
- 'advertisement/<int:pk>/edit/' (Путь к форме редактирования существующего объявления по его первичному ключу)
- 'advertisement/<int:pk>/delete/' (Путь к форме удаления объявления по его первичному ключу)
- 'advertisement/<int:pk>/like/' (Путь к форме для лайка )
- 'advertisement/<int:pk>/dislike/' (Путь к форме для дизлайка) 
"""

sprints5/sprint5_zad8/urban_project/urban_project/urls.py
"""
Конфигурация URL для проекта urban_project.
Список `urlpatterns` направляет URL в представления. Для получения дополнительной информации см.:
https://docs.djangoproject.com/en/5.0/topics/http/urls/
Примеры:
Функциональные представления
1. Добавьте импорт: from my_app import views
2. Добавьте URL в urlpatterns: path('', views.home, name='home')
Представления на основе классов
1. Добавьте импорт: from other_app.views import Home
2. Добавьте URL в urlpatterns: path('', Home.as_view(), name='home')
Включение другого URLconf
1. Импортируйте функцию include(): from django.urls import include, path
2. Добавьте URL в urlpatterns: path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from board import views as board_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls', namespace='board')),
    path('accounts/logout/', board_views.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', board_views.home, name='home'),
    path('signup/', board_views.signup, name='signup'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sprints5/sprint5_zad8/urban_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Django Project{% endblock %}</title>
    <style>
        .navbar {
            overflow: hidden;
            background-color: #333;
            padding: 14px 16px;
        }
        .navbar a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 12px;
            text-decoration: none;
            font-size: 17px;
        }
        .navbar a:hover {
            background-color: #ddd;
            color: black;
        }
    </style>
</head>
<body>

    <div class="navbar">
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'board:advertisement_list' %}">Board</a>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
            <a href="{% url 'board:add_advertisement' %}"><button>Add</button></a> <!-- Исправлено: Добавлена кнопка ADD -->
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'signup' %}">Sign Up</a>
        {% endif %}
    </div>

    <div>
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

sprints5/sprint5_zad8/urban_project/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
    <h1>Welcome to Our Site!</h1>
    <p><a href="/board/">Go to the board</a></p>
</body>
</html>