sprints5/sprint5_zad8/urban_project/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.advertisement_list, name='advertisement_list'),
    path('advertisement/<int:pk>/', views.advertisement_detail, name='advertisement_detail'),
    path('add/', views.add_advertisement, name='add_advertisement'),
    path('advertisement/<int:pk>/edit/', views.edit_advertisement, name='edit_advertisement'),  # Новый URL для редактирования
    path('advertisement/<int:pk>/delete/', views.delete_advertisement, name='delete_advertisement'),  # Новый URL для удаления объявления
    path('advertisement/<int:pk>/like/', views.like_advertisement, name='like_advertisement'),   # Новый URL для лайка
    path('advertisement/<int:pk>/dislike/', views.dislike_advertisement, name='dislike_advertisement'),  # Новый URL для дизлайка
]

"""
URL-шаблоны для приложения 'board'.

Доступные маршруты:
- '' (Путь к списку объявлений)
- 'advertisement/<int:pk>/' (Путь к деталям объявления по его первичному ключу)
- 'add/' (Путь к форме добавления нового объявления)
- 'advertisement/<int:pk>/edit/' (Путь к форме редактирования существующего объявления по его первичному ключу)
- 'advertisement/<int:pk>/delete/' (Путь к форме удаления объявления по его первичному ключу)
- 'advertisement/<int:pk>/like/' (Путь к форме для лайка )
- 'advertisement/<int:pk>/dislike/' (Путь к форме для дизлайка) 
"""

sprints5/sprint5_zad8/urban_project/urban_project/urls.py
"""
Конфигурация URL для проекта urban_project.
Список `urlpatterns` направляет URL в представления. Для получения дополнительной информации см.:
https://docs.djangoproject.com/en/5.0/topics/http/urls/
Примеры:
Функциональные представления
1. Добавьте импорт: from my_app import views
2. Добавьте URL в urlpatterns: path('', views.home, name='home')
Представления на основе классов
1. Добавьте импорт: from other_app.views import Home
2. Добавьте URL в urlpatterns: path('', Home.as_view(), name='home')
Включение другого URLconf
1. Импортируйте функцию include(): from django.urls import include, path
2. Добавьте URL в urlpatterns: path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from board import views as board_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls', namespace='board')),
    path('accounts/logout/', board_views.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', board_views.home, name='home'),
    path('signup/', board_views.signup, name='signup'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sprints5/sprint5_zad8/urban_project/board/models.py
from django.db import models
from django.contrib.auth.models import User


class Advertisement(models.Model):
    """
    Модель объявления.

    Атрибуты:
        title (CharField): Заголовок объявления, максимальная длина 255 символов.
        content (TextField): Содержимое объявления.
        author (ForeignKey): Пользователь, создавший объявление (внешний ключ на модель User).
        created_at (DateTimeField): Дата и время создания объявления (автоматически добавляется).
        image (ImageField): Изображение объявления, загружается в папку 'advertisements/',
                            может быть null или пустым.
        like:  Поле для подсчета лайков;
        dislike:  Поле для подсчета дизлайков;
    """
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='advertisements/', null=True, blank=True)
    likes = models.IntegerField(default=0)  # Поле для подсчета лайков
    dislikes = models.IntegerField(default=0)  # Поле для подсчета дизлайков


    def __str__(self):
        """
        Возвращает строковое представление объявления.

        Возвращает:
            str: Заголовок объявления.
        """
        return self.title


class Comment(models.Model):
    """
    Модель комментария к объявлению.

    Атрибуты:
        advertisement (ForeignKey): Объявление, к которому принадлежит комментарий
                                    (внешний ключ на модель Advertisement).
        author (ForeignKey): Пользователь, оставивший комментарий (внешний ключ на модель User).
        content (TextField): Содержимое комментария.
        created_at (DateTimeField): Дата и время создания комментария (автоматически добавляется).
    """
    advertisement = models.ForeignKey(Advertisement, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Возвращает строковое представление комментария.

        Возвращает:
            str: Строка в формате 'Комментарий от {автор} к {объявлению}'.
        """
        return f'Comment by {self.author} on {self.advertisement}'


class UserProfile(models.Model):
    """
    Модель профиля пользователя.

    Эта модель хранит статистику пользователя, включая общее количество созданных и удалённых объявлений,
    а также количество лайков и дизлайков, выставленных пользователем.

    Атрибуты:
        user (OneToOneField): Связь с моделью User.
        created_ads_count (PositiveIntegerField): Количество объявлений, созданных пользователем.
        deleted_ads_count (PositiveIntegerField): Количество объявлений, удалённых пользователем.
        likes_count (PositiveIntegerField): Общее количество лайков, выставленных пользователем.
        dislikes_count (PositiveIntegerField): Общее количество дизлайков, выставленных пользователем.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_ads_count = models.PositiveIntegerField(default=0)
    deleted_ads_count = models.PositiveIntegerField(default=0)
    likes_count = models.PositiveIntegerField(default=0)
    dislikes_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        """
        Возвращает строковое представление профиля пользователя, отображая имя пользователя.
        """
        return self.user.username

sprints5/sprint5_zad8/urban_project/board/forms.py
from django import forms
from .models import Advertisement
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AdvertisementForm(forms.ModelForm):
    """
    Форма для создания и редактирования объявления.

    Класс наследуется от ModelForm и автоматически генерирует форму на основе
    модели Advertisement.

    Атрибуты:
        Meta (класс): Внутренний класс, определяющий модель и поля формы.
    """

    class Meta:
        model = Advertisement  # Модель, на основе которой создается форма
        fields = ['title', 'content', 'author', 'image']  # Поля модели, которые будут включены в форму


class SignUpForm(UserCreationForm):
    """
    Форма для регистрации нового пользователя.

    Класс наследуется от UserCreationForm, который предоставляет функциональность
    для создания нового пользователя с использованием стандартных полей
    (имя пользователя и пароль).

    Атрибуты:
        Meta (класс): Внутренний класс, определяющий модель и поля формы.
    """

    class Meta:
        model = User  # Модель, на основе которой создается форма
        fields = ('username', 'password1', 'password2',)  # Поля для регистрации

sprints5/sprint5_zad8/urban_project/board/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from .models import Advertisement
from .forms import AdvertisementForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404
from .forms import SignUpForm
from django.contrib.auth import login
from .models import UserProfile


def logout_view(request):
    """
    Обрабатывает выход пользователя из системы.

    Аргументы:
        request: Объект HTTP-запроса.

    Возвращает:
        Перенаправление на главную страницу после выхода.
    """
    logout(request)
    return redirect('home')


def signup(request):
    """
    Обрабатывает регистрацию нового пользователя.

    Если метод запроса POST, форма регистрации обрабатывается. Пользователь
    создаётся и автоматически авторизуется, а также создаётся профиль пользователя.

    Аргументы:
        request: Объект HTTP-запроса.

    Возвращает:
        Отображает страницу регистрации или перенаправляет на доску после успешной регистрации.
    """
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            UserProfile.objects.create(user=user)  # Создание профиля пользователя
            login(request, user)
            return redirect('/board')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def home(request):
    """
    Отображает главную страницу.

    Аргументы:
        request: Объект HTTP-запроса.

    Возвращает:
        Отображает шаблон главной страницы.
    """
    return render(request, 'home.html')


def advertisement_list(request):
    """
    Отображает список всех объявлений.

    Аргументы:
        request: Объект HTTP-запроса.

    Возвращает:
        Отображает шаблон списка объявлений со всеми объявлениями.
    """
    advertisements = Advertisement.objects.all()
    paginator = Paginator(advertisements, 7)  # Отображаем 7 объявлений на странице

    page_number = request.GET.get('page')  # Получаем номер страницы из URL-параметров
    page_obj = paginator.get_page(page_number)  # Получаем объявления для текущей страницы

    return render(request, 'board/advertisement_list.html', {'page_obj': page_obj})


def advertisement_detail(request, pk):
    """
    Отображает подробности конкретного объявления.

    Аргументы:
        request: Объект HTTP-запроса.
        pk: Первичный ключ объявления для получения.

    Возвращает:
        Отображает шаблон детализации объявления для указанного объявления.
    """
    advertisement = Advertisement.objects.get(pk=pk)
    return render(request, 'board/advertisement_detail.html', {'advertisement': advertisement})


@login_required
def add_advertisement(request):
    """
    Обрабатывает создание нового объявления.

    Если метод запроса POST, обрабатывает форму объявления.
    Если форма действительна, объявление сохраняется с текущим пользователем как автором.

    Аргументы:
        request: Объект HTTP-запроса.

    Возвращает:
        Отображает форму добавления объявления или перенаправляет на список объявлений после сохранения.
    """
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.author = request.user
            advertisement.save()

            # Обновляем счетчик созданных объявлений у профиля пользователя
            user_profile, created = UserProfile.objects.get_or_create(user=request.user)
            user_profile.created_ads_count += 1  # Увеличиваем счетчик созданных объявлений
            print(f"Объявление создано: {advertisement.title}, Автор: {request.user.username}")
            print(f"Обновлен счетчик созданных объявлений: {user_profile.created_ads_count}")
            user_profile.save()

            return redirect('board:advertisement_list')
    else:
        form = AdvertisementForm()

    return render(request, 'board/add_advertisement.html', {'form': form})


@login_required
def edit_advertisement(request, pk):
    """
    Обрабатывает редактирование существующего объявления.

    Убедитесь, что объявление принадлежит текущему пользователю.
    Если метод запроса POST, обрабатывает форму для объявления.

    Аргументы:
        request: Объект HTTP-запроса.
        pk: Первичный ключ объявления для редактирования.

    Возвращает:
        Отображает форму редактирования объявления или перенаправляет на список объявлений после сохранения.
    """
    advertisement = get_object_or_404(Advertisement, pk=pk, author=request.user)
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES, instance=advertisement)  # Обработка изображений
        if form.is_valid():
            form.save()
            return redirect('board:advertisement_list')
    else:
        form = AdvertisementForm(instance=advertisement)
    return render(request, 'board/edit_advertisement.html', {'form': form, 'advertisement': advertisement})


@login_required
def delete_advertisement(request, pk):
    """
    Обрабатывает удаление объявления.

    Убедитесь, что объявление принадлежит текущему пользователю.
    Если метод запроса POST, объявление удаляется.

    Аргументы:
        request: Объект HTTP-запроса.
        pk: Первичный ключ объявления для удаления.

    Возвращает:
        отображает подтверждение удаления объявления или перенаправляет на список объявлений после удаления.
    """
    advertisement = get_object_or_404(Advertisement, pk=pk, author=request.user)

    if request.method == "POST":
        # Здесь обновляем счетчик удаленных объявлений у профиля пользователя
        user_profile, created = UserProfile.objects.get_or_create(user=request.user)
        user_profile.deleted_ads_count += 1  # Увеличиваем счетчик удалённых объявлений
        user_profile.save()

        advertisement.delete()  # Удаление объявления
        return redirect('board:advertisement_list')  # Перенаправление на список объявлений

    return render(request, 'board/delete_advertisement.html', {'advertisement': advertisement})


@login_required
def like_advertisement(request, pk):
    """
    Обрабатывает лайк к объявлению.
    """
    advertisement = get_object_or_404(Advertisement, pk=pk)

    # Убедитесь, что профиль пользователя существует
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)

    # Обновляем количество лайков в объявлении
    advertisement.likes += 1
    advertisement.save()

    # Обновляем количество лайков у профиля пользователя
    user_profile.likes_count += 1
    user_profile.save()

    return redirect('board:advertisement_detail', pk=pk)


#@login_required
#def dislike_advertisement(request, pk):
#    """
#    Обрабатывает дизлайк к объявлению.
#   Увеличивает счетчик дизлайков на 1.
#    """
#    advertisement = get_object_or_404(Advertisement, pk=pk)
#    advertisement.dislikes += 1
#    advertisement.save()
#    return redirect('board:advertisement_detail', pk=pk)


#@login_required
#def like_advertisement(request, pk):
#    """
#    Обрабатывает действие лайка к объявлению.

#    Увеличивает счётчик лайков объявления и счётчик лайков пользователя.

#   Аргументы:
#        request: Объект HTTP-запроса.
#        pk: Первичный ключ объявления для лайка.

#    Возвращает:
#        Перенаправление на страницу детализации объявления.
#    """
#    advertisement = get_object_or_404(Advertisement, pk=pk)
#    advertisement.likes += 1
#    advertisement.save()

#    advertisement.author.userprofile.likes_count += 1
#    advertisement.author.userprofile.save()

#    return redirect('board:advertisement_detail', pk=pk)


@login_required
def dislike_advertisement(request, pk):
    """
    Обрабатывает действие дизлайка к объявлению.

    Увеличивает счётчик дизлайков объявления и счётчик дизлайков пользователя.

    Аргументы:
        request: Объект HTTP-запроса.
        pk: Первичный ключ объявления для дизлайка.

    Возвращает:
        Перенаправление на страницу детализации объявления.
    """
    advertisement = get_object_or_404(Advertisement, pk=pk)
    advertisement.dislikes += 1
    advertisement.save()

    advertisement.author.userprofile.dislikes_count += 1
    advertisement.author.userprofile.save()

    return redirect('board:advertisement_detail', pk=pk)


sprints5/sprint5_zad8/urban_project/board/templates/board/add_advertisement.html
{% extends 'base.html' %}

{% block content %}
  <h2>Add Advertisement</h2>
  <form method="post" enctype="multipart/form-data"> <!-- Обратите внимание на enctype -->
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

sprints5/sprint5_zad8/urban_project/board/templates/board/advertisement_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ advertisement.title }}</h1>
<p>{{ advertisement.content }}</p>

{% if advertisement.image %}
    <img src="{{ advertisement.image.url }}" alt="{{ advertisement.title }}" style="max-width: 100%;">
{% endif %}
<p>(Автор: {{ advertisement.author.username }})</p>

<!-- Кнопки для лайков и дизлайков -->
<div>
    <span>(+) {{ advertisement.likes }}</span>
    <a href="{% url 'board:like_advertisement' pk=advertisement.pk %}">Like</a>
    <span>(-) {{ advertisement.dislikes }}</span>
    <a href="{% url 'board:dislike_advertisement' pk=advertisement.pk %}">Dislike</a>
</div>

{% endblock %}

sprints5/sprint5_zad8/urban_project/board/templates/board/advertisement_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Advertisements</h1>

{% if user.is_authenticated %}
<h2>Your Advertisements:</h2>
<p>{{ user.username }} создал: {{ user.userprofile.created_ads_count }} / удалил: {{ user.userprofile.deleted_ads_count }}</p>
<p>Поставил: (+) {{ user.userprofile.likes_count }} / (-) {{ user.userprofile.dislikes_count }}</p>
<ul>
{% for advertisement in page_obj %}
    {% if advertisement.author == user %}
    <li>
        <a href="{% url 'board:advertisement_detail' pk=advertisement.pk %}">{{ advertisement.title }}</a>
        <a href="{% url 'board:edit_advertisement' pk=advertisement.pk %}">Edit</a>
        <a href="{% url 'board:delete_advertisement' pk=advertisement.pk %}">Delete</a>
        {% if advertisement.image %}
        <img src="{{ advertisement.image.url }}" alt="{{ advertisement.title }}" style="max-width: 100px; display: block; margin-top: 5px;">
        {% endif %}
        <span>(+) {{ advertisement.likes }}</span> <!-- Количество лайков -->
        <span>(-) {{ advertisement.dislikes }}</span> <!-- Количество дизлайков -->
        <p>(Автор: {{ advertisement.author.username }})</p> <!-- Автор объявления -->
    </li>
    {% endif %}
{% endfor %}
</ul>
{% endif %}

<h2>Other Advertisements:</h2>
<ul>
{% for advertisement in page_obj %}
    {% if advertisement.author != user %}
    <li>
        <a href="{% url 'board:advertisement_detail' pk=advertisement.pk %}">{{ advertisement.title }}</a>
        <span>(+) {{ advertisement.likes }}</span>
        <span>(-) {{ advertisement.dislikes }}</span>
    </li>
    {% endif %}
{% endfor %}
</ul>

<!-- Элементы управления пагинацией -->
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

sprints5/sprint5_zad8/urban_project/board/templates/board/delete_advertisement.html
{% extends 'base.html' %}

{% block content %}
<h1>Confirm deletion of advertisement: "{{ advertisement.title }}"</h1>
<p>Are you sure you want to delete this advertisement?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete it</button>
</form>

<a href="{% url 'board:advertisement_list' %}">Cancel</a>
{% endblock %}

sprints5/sprint5_zad8/urban_project/board/templates/board/edit_advertisement.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit Advertisement: {{ advertisement.title }}</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
</form>

<a href="{% url 'board:advertisement_list' %}">Cancel</a>
{% endblock %}